name: Push to master

on:
  push:
    branches:
      - master
    paths:
      - '*.bazel'
      - '.bazelrc'
      - '.github/workflows/**.yml'
      - 'PACE'
      - 'VERSION'
      - 'bazel/**'
      - 'pkg/**'


jobs:
  urbit:
    uses: ./.github/workflows/shared.yml
    with:
      pace: 'live'
      upload: true
      fake_tests: false
    secrets: inherit

  docker:
    uses: ./.github/workflows/docker-shared.yml
    with:
      pace: 'live'
    secrets: inherit
