name: Push to release

on:
  push:
    branches:
      - release
    paths:
      - '*.bazel'
      - '.bazelrc'
      - '.github/workflows/**.yml'
      - 'PACE'
      - 'VERSION'
      - 'bazel/**'
      - 'pkg/**'
  release:
    types: []

jobs:
  urbit:
    uses: ./.github/workflows/shared.yml
    with:
      docker: true
      pace: 'soon'
      upload: true
    secrets: inherit
